default:
  tags:
    - docker
  image: python:3.10-slim-buster

my_tests:
  # Good to put a small description here of what this job does
  script:
    - pip install -e -r requirements_dev.txt
    - pylint cdna
