name: scrna-seq-sim
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - argparse
  - biopython>=1.78
  - black
  - coverage
  - flake8
  - flake8-docstrings
  - gtfparse
  - polars==0.16.17
  - mypy
  - numpy>=1.23.3
  - pylint
  - pytest
  - nextflow
  - pandas>=1.4.4
  - pip>=20.2.3
  - python>=3.6, <=3.10
  - pip:
    - -e .
