name: transcript-sequence-extractor
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - pandas=1.5
  - numpy=1.23
  - gtfparse=1.2
  - pip=22.3
  - pytest=7.2
  - coverage=6.5
  - black=22.10
  - flake8=6.0
  - flake8-docstrings=1.6
  - mypy=0.991
  - pylint=2.15
  - bedtools=2.30
