default:
  tags:
    - docker
  image: python:3.10-slim-buster

stages:          # List of employment runs, starts with build ends with deploy. 
  - build
  - test

build-job:       # First stage deployment and installation of dependencies. 
  stage: build   # Build Stage
  script:
    - pip install -r requirements.txt
    - pip install -r requirements_dev.txt
    - pip install -e .
    - echo "Dependencies successfully deployed."

Coverage-test-job:   # Test Stage
  stage: test        # Starts when the above build stages finishes installing dependencies.
  script:
    - coverage run --source tests -m pytest
    - coverage report -m
    - echo "Coverage successfully deployed."

Flake8/Pylint/mypy-test-job:   # Test Stage
  stage: test    # Deploys and runs all 3 linters.
  script:
    - flake8 --docstring-convention google tests/tests/
    - pylint tests/ tests/
    - mypy tests/ tests/
    - echo "Linters successfully deployed."
