default:
  tags:
    - docker
  image: python:3.10-slim-buster

my_tests:
  # Good to put a small description here of what this job does
  before_script:
    - pip install -r requirements_dev.txt
  script:
    - echo "Command 1"
    - echo "Command 2"
