name: transcript-structure-generator
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - matplotlib
  - pandas
  - pip
  - flake8-docstrings
  - mypy
  - flake8
  - pytest
  - coverage
